try{
    console.log('started')
    console.log(messagee)
    throw('OHh no!')
}catch(error){
    console.log(error)
}
console.log('Completed')